// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TextArea from "./component/TextArea.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  React.useState(function () {
        return 0;
      });
  React.useState(function () {
        return "";
      });
  return JsxRuntime.jsx(TextArea.make, {});
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
